#!/usr/bin/env -S node
/**
 * Pull design tokens from a source of truth and open a PR only when a value changed.
 *
 *   node token_sync.ts sync --source tokens.json --target ./src/tokens.generated.ts
 *   node token_sync.ts --demo
 *
 * Designers change colors and spacing in a tool that exports JSON; developers
 * consume generated TypeScript constants. The sync has to be idempotent
 * (running it with nothing changed produces zero diff, not a reformatted
 * file) and has to flag a specific, useful kind of problem: a token that a
 * component in your codebase actually references being REMOVED upstream —
 * that's a build break waiting to happen, and it's worth surfacing loudly
 * instead of silently generating a file that no longer has the symbol.
 */

import * as fs from "node:fs";
import * as path from "node:path";

type TokenValue = string | number;
type TokenGroup = Record<string, TokenValue>;
interface TokenSource {
  color: TokenGroup;
  spacing: TokenGroup;
  radius: TokenGroup;
  fontSize: TokenGroup;
}

function toConstName(group: string, key: string): string {
  const parts = `${group}-${key}`.split(/[-_]/).filter(Boolean);
  // Only the leading character needs lowercasing (to make a valid, conventional
  // camelCase start) — lowercasing the WHOLE first segment was the bug: a group
  // name that's already camelCase internally (like "fontSize") got flattened to
  // "fontsize", producing "fontsizeBody" instead of "fontSizeBody".
  const head = parts[0][0].toLowerCase() + parts[0].slice(1);
  return head + parts.slice(1).map((p) => p[0].toUpperCase() + p.slice(1)).join("");
}

function formatValue(value: TokenValue): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

function generateTokenFile(tokens: TokenSource): string {
  const lines: string[] = [
    "// AUTO-GENERATED by token_sync.ts — do not edit by hand.",
    "// Source of truth lives in the design tool; re-run the sync to update this file.",
    "",
  ];
  for (const [group, values] of Object.entries(tokens)) {
    lines.push(`// ${group}`);
    for (const [key, value] of Object.entries(values as TokenGroup)) {
      lines.push(`export const ${toConstName(group, key)} = ${formatValue(value)};`);
    }
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}

interface TokenDiff {
  added: { name: string; value: TokenValue }[];
  removed: { name: string; value: TokenValue }[];
  changed: { name: string; from: TokenValue; to: TokenValue }[];
}

function flattenTokens(tokens: TokenSource): Map<string, TokenValue> {
  const flat = new Map<string, TokenValue>();
  for (const [group, values] of Object.entries(tokens)) {
    for (const [key, value] of Object.entries(values as TokenGroup)) {
      flat.set(toConstName(group, key), value);
    }
  }
  return flat;
}

function diffTokens(previous: TokenSource | null, current: TokenSource): TokenDiff {
  const prevFlat = previous ? flattenTokens(previous) : new Map<string, TokenValue>();
  const currFlat = flattenTokens(current);

  const added: TokenDiff["added"] = [];
  const removed: TokenDiff["removed"] = [];
  const changed: TokenDiff["changed"] = [];

  for (const [name, value] of currFlat) {
    if (!prevFlat.has(name)) added.push({ name, value });
    else if (prevFlat.get(name) !== value) changed.push({ name, from: prevFlat.get(name)!, to: value });
  }
  for (const [name, value] of prevFlat) {
    if (!currFlat.has(name)) removed.push({ name, value });
  }

  return { added, removed, changed };
}

/** Scan source files for `tokenName` identifiers that look like they were
 *  imported from the generated file, so a removed token that's still referenced
 *  somewhere gets flagged as a real break, not just a diff line. */
function findUsages(root: string, tokenNames: string[]): Map<string, string[]> {
  const usages = new Map<string, string[]>();
  const nameSet = new Set(tokenNames);
  function walk(dir: string): void {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "node_modules" || entry.name.startsWith(".") || entry.name.endsWith(".generated.ts")) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        continue;
      }
      if (!/\.tsx?$/.test(entry.name)) continue;
      const source = fs.readFileSync(full, "utf8");
      for (const name of nameSet) {
        const re = new RegExp(`\\b${name}\\b`);
        if (re.test(source)) {
          const list = usages.get(name) ?? [];
          list.push(full);
          usages.set(name, list);
        }
      }
    }
  }
  walk(root);
  return usages;
}

interface SyncResult {
  diff: TokenDiff;
  fileChanged: boolean;
  breakingRemovals: { name: string; usedIn: string[] }[];
}

function performSync(previous: TokenSource | null, current: TokenSource, previousFileContent: string | null, srcRoot: string): { result: SyncResult; newFileContent: string } {
  const diff = diffTokens(previous, current);
  const newFileContent = generateTokenFile(current);
  const fileChanged = newFileContent !== previousFileContent;

  const removedNames = diff.removed.map((r) => r.name);
  const usages = removedNames.length > 0 ? findUsages(srcRoot, removedNames) : new Map();
  const breakingRemovals = diff.removed
    .filter((r) => usages.has(r.name))
    .map((r) => ({ name: r.name, usedIn: usages.get(r.name)! }));

  return { result: { diff, fileChanged, breakingRemovals }, newFileContent };
}

function formatSyncResult(result: SyncResult): string {
  const lines: string[] = [];
  if (!result.fileChanged) {
    lines.push("No changes — the generated file already matches the source tokens.");
    return lines.join("\n");
  }

  lines.push(`${result.diff.added.length} added, ${result.diff.changed.length} changed, ${result.diff.removed.length} removed\n`);
  if (result.diff.added.length) {
    lines.push("added:");
    for (const a of result.diff.added) lines.push(`  + ${a.name} = ${formatValue(a.value)}`);
  }
  if (result.diff.changed.length) {
    lines.push("changed:");
    for (const c of result.diff.changed) lines.push(`  ~ ${c.name}: ${formatValue(c.from)} -> ${formatValue(c.to)}`);
  }
  if (result.diff.removed.length) {
    lines.push("removed:");
    for (const r of result.diff.removed) {
      const breaking = result.breakingRemovals.find((b) => b.name === r.name);
      lines.push(`  - ${r.name} = ${formatValue(r.value)}${breaking ? "  [STILL USED IN CODE]" : ""}`);
    }
  }

  if (result.breakingRemovals.length) {
    lines.push(`\nBREAKING: ${result.breakingRemovals.length} removed token(s) are still referenced in source:`);
    for (const b of result.breakingRemovals) {
      lines.push(`  ${b.name} used in:`);
      for (const file of b.usedIn) lines.push(`    ${file}`);
    }
  }

  return lines.join("\n");
}

// ------------------------------------------------------------ demo

function buildDemoProject(root: string): void {
  fs.rmSync(root, { recursive: true, force: true });
  const write = (rel: string, content: string): void => {
    const full = path.join(root, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content.trim() + "\n");
  };
  write(
    "Button.tsx",
    `
import { colorPrimary, spacingMd, radiusSm } from "./tokens.generated";

export function Button() {
  return { background: colorPrimary, padding: spacingMd, borderRadius: radiusSm };
}
`,
  );
  write(
    "Card.tsx",
    `
import { colorSurface, spacingLg } from "./tokens.generated";

export function Card() {
  return { background: colorSurface, padding: spacingLg };
}
`,
  );
}

function demo(): void {
  const root = "/tmp/token-sync-demo";
  buildDemoProject(root);
  console.log("(synthesised a small project with two components using generated tokens)\n");

  const previousTokens: TokenSource = {
    color: { primary: "#2563eb", surface: "#ffffff", danger: "#dc2626" },
    spacing: { sm: 4, md: 8, lg: 16 },
    radius: { sm: 4, md: 8 },
    fontSize: { body: 14, heading: 20 },
  };
  const previousFile = generateTokenFile(previousTokens);

  console.log("--- sync 1: nothing changed ---\n");
  const { result: result1 } = performSync(previousTokens, previousTokens, previousFile, root);
  console.log(formatSyncResult(result1));

  console.log("\n\n--- sync 2: designer updated the palette and removed the danger color ---\n");
  const currentTokens: TokenSource = {
    color: { primary: "#1d4ed8", surface: "#ffffff" }, // primary changed, danger removed
    spacing: { sm: 4, md: 8, lg: 16, xl: 24 }, // xl added
    radius: { sm: 4, md: 8 },
    fontSize: { body: 14, heading: 20 },
  };
  const { result: result2, newFileContent } = performSync(previousTokens, currentTokens, previousFile, root);
  console.log(formatSyncResult(result2));

  console.log("\n\n--- sync 3: designer also removes 'colorSurface', which Card.tsx still imports ---\n");
  const breakingTokens: TokenSource = {
    color: { primary: "#1d4ed8" }, // surface removed too — but Card.tsx uses colorSurface!
    spacing: { sm: 4, md: 8, lg: 16, xl: 24 },
    radius: { sm: 4, md: 8 },
    fontSize: { body: 14, heading: 20 },
  };
  const { result: result3 } = performSync(currentTokens, breakingTokens, newFileContent, root);
  console.log(formatSyncResult(result3));

  console.log(`\n\nnote: sync 1 (identical tokens) correctly reports zero changes — an idempotent`);
  console.log(`re-run doesn't reformat or touch the file. sync 2 removed "danger", which nothing`);
  console.log(`in the demo project imports, so it's a clean removal. sync 3 removes "surface"`);
  console.log(`(colorSurface), which Card.tsx DOES import — that's flagged as BREAKING with the`);
  console.log(`exact file, because generating a token file that's missing a symbol a component`);
  console.log(`still imports is a build break, not a routine diff.`);

  fs.rmSync(root, { recursive: true, force: true });
}

// ------------------------------------------------------------ CLI

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.includes("--demo") || args.length === 0) {
    demo();
    return;
  }

  if (args[0] !== "sync") {
    console.log("usage: token_sync.ts sync --source tokens.json --target ./src/tokens.generated.ts");
    return;
  }
  const get = (flag: string): string | undefined => {
    const idx = args.indexOf(flag);
    return idx >= 0 ? args[idx + 1] : undefined;
  };
  const sourcePath = get("--source");
  const targetPath = get("--target");
  if (!sourcePath || !targetPath) {
    console.error("--source and --target are required");
    process.exitCode = 1;
    return;
  }

  const current = JSON.parse(fs.readFileSync(sourcePath, "utf8")) as TokenSource;
  const previousFileContent = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, "utf8") : null;
  // without a stored previous JSON snapshot, treat "no target file yet" as no previous state
  const previous: TokenSource | null = null;

  const { result, newFileContent } = performSync(previous, current, previousFileContent, path.dirname(targetPath));
  console.log(formatSyncResult(result));

  if (result.fileChanged) {
    fs.writeFileSync(targetPath, newFileContent);
    console.log(`\nwrote ${targetPath}`);
  }
  if (result.breakingRemovals.length) process.exitCode = 1;
}

main();
